<a href="https://colab.research.google.com/github/taka-yoko/jupyter_notebook_n_school_data_analysis_test/blob/master/N%E4%BA%88%E5%82%99%E6%A0%A1_%E3%83%87%E3%83%BC%E3%82%BF%E3%81%AE%E5%88%86%E6%9E%90%E3%83%86%E3%82%B9%E3%83%88.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
ar = np.array([96, 60, 28, 15, 89, 85, 47, 70, 18, 56, 76, 80, 2, 52, 36])

In [ ]:
np.average(ar)

54.0

In [ ]:
np.max(ar)

96

In [ ]:
np.median(ar)

56.0

In [ ]:
q25, q75 = np.percentile(ar, [25, 75])

In [ ]:
iqr = q75 - q25

In [ ]:
print("25%点", q25)
print("75%点", q75)
print("四分位範囲", iqr)

25%点 32.0
75%点 78.0
四分位範囲 46.0


In [ ]:
 np.percentile(ar, [50])

array([56.])

In [ ]:
ar

array([96, 60, 28, 15, 89, 85, 47, 70, 18, 56, 76, 80,  2, 52, 36])

In [ ]:
np.sort(ar)

array([ 2, 15, 18, 28, 36, 47, 52, 56, 60, 70, 76, 80, 85, 89, 96])

In [ ]:
ar2 = np.array([6, 9, 7, 4, 12, 10])
np.var(ar2)

7.0

In [ ]:
np.std(ar2)

2.6457513110645907

# 新しいセクション